---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-nginx
  name: my-nginx
  namespace: default
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""
spec:
  ports:
  - nodePort: 31111
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-nginx
  sessionAffinity: None
  type: NodePort
